[package]
name = "ordan"
version = "1.0.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
jlnexus = { git = "https://www.github.com/verdex/jlnexus", version = "2.0.0", tag = "release-2.0.0" }
